import {
  PDFDocument,
  PDFFont,
  PDFImage,
  StandardFonts,
  rgb,
} from "pdf-lib";

import {
  NextRequest,
  NextResponse,
} from "next/server";

import {
  ErroBiblioteca,
  exigirPermissaoBiblioteca,
  obterContextoBiblioteca,
  respostaErroBiblioteca,
} from "@/lib/biblioteca-acesso";

import {
  getUserFromToken,
} from "@/lib/server-auth";

import {
  prisma,
} from "@/lib/prisma";

import {
  GET as obterRelatorio,
} from "../route";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const revalidate = 0;

type Relatorio = {
  periodo: {
    inicio: string;
    fim: string;
  };

  circulacao: {
    emprestimos: number;
    devolucoes: number;
  };

  renovacoes: {
    total: number;
  };

  reservas: {
    total: number;
  };

  multas: {
    quantidade: number;
    valorGerado: number;
    valorPago: number;
    valorEmAberto: number;
  };

  acervo: {
    titulos: number;
    exemplares: number;
    porStatus: Record<string, number>;
  };

  digital: {
    acessos: number;
    usuariosUnicos: number;
    visualizacoes: number;
    leiturasConcluidas: number;
  };

  rankings: {
    itensMaisEmprestados: Array<{
      itemId: number;
      titulo: string;
      subtitulo: string | null;
      quantidade: number;
    }>;

    usuariosMaisAtivos: Array<{
      usuarioId: number;
      nome: string;
      email: string | null;
      quantidade: number;
    }>;
  };
};

const ROTULOS = {
  "pt-BR": {
    titulo: "Relatório Gerencial da Biblioteca",
    periodo: "Período",
    circulacao: "Circulação",
    emprestimos: "Empréstimos",
    devolucoes: "Devoluções",
    renovacoes: "Renovações",
    reservas: "Reservas",
    multas: "Multas",
    multasGeradas: "Multas geradas",
    valorGerado: "Valor gerado",
    valorPago: "Valor pago",
    valorAberto: "Valor em aberto",
    acervo: "Acervo",
    titulos: "Títulos",
    exemplares: "Exemplares",
    disponiveis: "Disponíveis",
    indisponiveis: "Indisponíveis",
    digital: "Uso digital",
    acessos: "Acessos digitais",
    usuariosUnicos: "Usuários únicos",
    visualizacoes: "Visualizações",
    leiturasConcluidas: "Leituras concluídas",
    maisEmprestados: "Itens mais emprestados",
    usuariosAtivos: "Usuários mais ativos",
    emprestimoQtd: "empréstimo",
    emprestimosQtd: "empréstimos",
    semDados: "Nenhum registro no período.",
    gerado: "Gerado pelo PHANYX",
    pagina: "Página",
    de: "de",
  },

  "pt-PT": {
    titulo: "Relatório de Gestão da Biblioteca",
    periodo: "Período",
    circulacao: "Circulação",
    emprestimos: "Empréstimos",
    devolucoes: "Devoluções",
    renovacoes: "Renovações",
    reservas: "Reservas",
    multas: "Multas",
    multasGeradas: "Multas geradas",
    valorGerado: "Valor gerado",
    valorPago: "Valor pago",
    valorAberto: "Valor em aberto",
    acervo: "Acervo",
    titulos: "Títulos",
    exemplares: "Exemplares",
    disponiveis: "Disponíveis",
    indisponiveis: "Indisponíveis",
    digital: "Utilização digital",
    acessos: "Acessos digitais",
    usuariosUnicos: "Utilizadores únicos",
    visualizacoes: "Visualizações",
    leiturasConcluidas: "Leituras concluídas",
    maisEmprestados: "Itens mais emprestados",
    usuariosAtivos: "Utilizadores mais ativos",
    emprestimoQtd: "empréstimo",
    emprestimosQtd: "empréstimos",
    semDados: "Nenhum registo no período.",
    gerado: "Gerado pelo PHANYX",
    pagina: "Página",
    de: "de",
  },

  "en-US": {
    titulo: "Library Management Report",
    periodo: "Period",
    circulacao: "Circulation",
    emprestimos: "Loans",
    devolucoes: "Returns",
    renovacoes: "Renewals",
    reservas: "Reservations",
    multas: "Fines",
    multasGeradas: "Fines generated",
    valorGerado: "Amount generated",
    valorPago: "Amount paid",
    valorAberto: "Outstanding amount",
    acervo: "Collection",
    titulos: "Titles",
    exemplares: "Copies",
    disponiveis: "Available",
    indisponiveis: "Unavailable",
    digital: "Digital usage",
    acessos: "Digital accesses",
    usuariosUnicos: "Unique users",
    visualizacoes: "Views",
    leiturasConcluidas: "Completed reads",
    maisEmprestados: "Most borrowed items",
    usuariosAtivos: "Most active users",
    emprestimoQtd: "loan",
    emprestimosQtd: "loans",
    semDados: "No records for the selected period.",
    gerado: "Generated by PHANYX",
    pagina: "Page",
    de: "of",
  },

  "es-ES": {
    titulo: "Informe de Gestión de la Biblioteca",
    periodo: "Período",
    circulacao: "Circulación",
    emprestimos: "Préstamos",
    devolucoes: "Devoluciones",
    renovacoes: "Renovaciones",
    reservas: "Reservas",
    multas: "Multas",
    multasGeradas: "Multas generadas",
    valorGerado: "Valor generado",
    valorPago: "Valor pagado",
    valorAberto: "Valor pendiente",
    acervo: "Colección",
    titulos: "Títulos",
    exemplares: "Ejemplares",
    disponiveis: "Disponibles",
    indisponiveis: "No disponibles",
    digital: "Uso digital",
    acessos: "Accesos digitales",
    usuariosUnicos: "Usuarios únicos",
    visualizacoes: "Visualizaciones",
    leiturasConcluidas: "Lecturas completadas",
    maisEmprestados: "Ítems más prestados",
    usuariosAtivos: "Usuarios más activos",
    emprestimoQtd: "préstamo",
    emprestimosQtd: "préstamos",
    semDados: "No hay registros en el período.",
    gerado: "Generado por PHANYX",
    pagina: "Página",
    de: "de",
  },

  "fr-FR": {
    titulo: "Rapport de gestion de la bibliothèque",
    periodo: "Période",
    circulacao: "Circulation",
    emprestimos: "Emprunts",
    devolucoes: "Retours",
    renovacoes: "Renouvellements",
    reservas: "Réservations",
    multas: "Amendes",
    multasGeradas: "Amendes générées",
    valorGerado: "Montant généré",
    valorPago: "Montant payé",
    valorAberto: "Montant restant",
    acervo: "Collection",
    titulos: "Titres",
    exemplares: "Exemplaires",
    disponiveis: "Disponibles",
    indisponiveis: "Indisponibles",
    digital: "Usage numérique",
    acessos: "Accès numériques",
    usuariosUnicos: "Utilisateurs uniques",
    visualizacoes: "Consultations",
    leiturasConcluidas: "Lectures terminées",
    maisEmprestados: "Documents les plus empruntés",
    usuariosAtivos: "Utilisateurs les plus actifs",
    emprestimoQtd: "emprunt",
    emprestimosQtd: "emprunts",
    semDados: "Aucun enregistrement pour la période.",
    gerado: "Généré par PHANYX",
    pagina: "Page",
    de: "sur",
  },
} as const;

type LocaleRelatorio =
  keyof typeof ROTULOS;

function obterLocale(
  valor: string | null,
): LocaleRelatorio {
  if (
    valor &&
    Object.prototype.hasOwnProperty.call(
      ROTULOS,
      valor,
    )
  ) {
    return valor as LocaleRelatorio;
  }

  return "pt-BR";
}

function limparEspacosPdf(
  valor: string,
) {
  return valor
    .replace(/\u00a0/g, " ")
    .replace(/\u202f/g, " ");
}

function formatarData(
  valor: string,
  locale: string,
) {
  return new Date(
    `${valor}T12:00:00.000Z`,
  ).toLocaleDateString(
    locale,
  );
}

function cortarTexto(
  texto: string,
  fonte: PDFFont,
  tamanho: number,
  largura: number,
) {
  let resultado =
    texto || "-";

  if (
    fonte.widthOfTextAtSize(
      resultado,
      tamanho,
    ) <= largura
  ) {
    return resultado;
  }

  while (
    resultado.length > 3 &&
    fonte.widthOfTextAtSize(
      `${resultado}...`,
      tamanho,
    ) > largura
  ) {
    resultado =
      resultado.slice(
        0,
        -1,
      );
  }

  return `${resultado}...`;
}

async function carregarLogo(
  pdf: PDFDocument,
  url: string | null | undefined,
  origem: string,
): Promise<PDFImage | null> {
  if (!url) {
    return null;
  }

  try {
    const urlFinal =
      url.startsWith("http://") ||
      url.startsWith("https://")
        ? url
        : `${origem}${url.startsWith("/") ? "" : "/"}${url}`;

    const resposta =
      await fetch(
        urlFinal,
        {
          cache:
            "no-store",
        },
      );

    if (!resposta.ok) {
      return null;
    }

    const bytes =
      await resposta.arrayBuffer();

    try {
      return await pdf.embedPng(
        bytes,
      );
    } catch {
      try {
        return await pdf.embedJpg(
          bytes,
        );
      } catch {
        return null;
      }
    }
  } catch {
    return null;
  }
}

export async function GET(
  request: NextRequest,
) {
  try {
    const usuario =
      await getUserFromToken();

    if (!usuario) {
      throw new ErroBiblioteca(
        401,
        "Usuario nao autenticado.",
        "NAO_AUTENTICADO",
      );
    }

    const contexto =
      await obterContextoBiblioteca(
        usuario,
      );

    exigirPermissaoBiblioteca(
      usuario,
      contexto,
      "biblioteca.relatorios.ver",
    );

    exigirPermissaoBiblioteca(
      usuario,
      contexto,
      "biblioteca.relatorios.exportar",
    );

    const resposta =
      await obterRelatorio(
        request,
      );

    if (!resposta.ok) {
      return resposta;
    }

    const dados =
      (await resposta.json()) as Relatorio;

    const locale =
      obterLocale(
        request.nextUrl.searchParams.get(
          "locale",
        ),
      );

    const r =
      ROTULOS[locale];

    const [
      instituicao,
      configuracao,
    ] =
      await Promise.all([
        prisma.instituicao.findUnique({
          where: {
            id:
              contexto.instituicaoId,
          },
          select: {
            nome: true,
          },
        }),

        prisma.configuracaoInstituicao.findUnique({
          where: {
            instituicaoId:
              contexto.instituicaoId,
          },
          select: {
            nomeFantasia: true,
            razaoSocial: true,
            cnpj: true,
            telefone: true,
            email: true,
            cidade: true,
            estado: true,
            logoUrl: true,
          },
        }),
      ]);

    const nomeInstituicao =
      configuracao?.nomeFantasia ||
      configuracao?.razaoSocial ||
      instituicao?.nome ||
      "PHANYX";

    const pdf =
      await PDFDocument.create();

    pdf.setTitle(
      r.titulo,
    );

    pdf.setAuthor(
      "PHANYX",
    );

    pdf.setCreator(
      "PHANYX",
    );

    pdf.setProducer(
      "PHANYX",
    );

    const normal =
      await pdf.embedFont(
        StandardFonts.Helvetica,
      );

    const bold =
      await pdf.embedFont(
        StandardFonts.HelveticaBold,
      );

    const logo =
      await carregarLogo(
        pdf,
        configuracao?.logoUrl,
        request.nextUrl.origin,
      );

    const largura = 842;
    const altura = 595;
    const margem = 34;

    const azul =
      rgb(
        0.145,
        0.388,
        0.922,
      );

    const azulClaro =
      rgb(
        0.94,
        0.97,
        1,
      );

    const cinza =
      rgb(
        0.39,
        0.45,
        0.55,
      );

    const cinzaClaro =
      rgb(
        0.965,
        0.973,
        0.984,
      );

    const borda =
      rgb(
        0.82,
        0.85,
        0.9,
      );

    function desenharCabecalho(
      pagina: ReturnType<
        typeof pdf.addPage
      >,
    ) {
      let x =
        margem;

      if (logo) {
        const escala =
          Math.min(
            70 /
              logo.width,
            45 /
              logo.height,
          );

        const w =
          logo.width *
          escala;

        const h =
          logo.height *
          escala;

        pagina.drawImage(
          logo,
          {
            x: margem,
            y:
              altura -
              margem -
              h,
            width: w,
            height: h,
          },
        );

        x =
          margem +
          85;
      }

      pagina.drawText(
        cortarTexto(
          nomeInstituicao,
          bold,
          15,
          largura -
            x -
            margem,
        ),
        {
          x,
          y:
            altura -
            margem -
            2,
          size: 15,
          font: bold,
          color:
            rgb(
              0.06,
              0.09,
              0.16,
            ),
        },
      );

      pagina.drawText(
        r.titulo,
        {
          x,
          y:
            altura -
            margem -
            23,
          size: 12,
          font: bold,
          color: azul,
        },
      );

      pagina.drawText(
        `${r.periodo}: ${formatarData(
          dados.periodo.inicio,
          locale,
        )} - ${formatarData(
          dados.periodo.fim,
          locale,
        )}`,
        {
          x,
          y:
            altura -
            margem -
            42,
          size: 9,
          font: normal,
          color: cinza,
        },
      );

      pagina.drawLine({
        start: {
          x: margem,
          y:
            altura -
            98,
        },
        end: {
          x:
            largura -
            margem,
          y:
            altura -
            98,
        },
        thickness:
          0.8,
        color: borda,
      });
    }

    function tituloSecao(
      pagina: ReturnType<
        typeof pdf.addPage
      >,
      titulo: string,
      y: number,
    ) {
      pagina.drawText(
        titulo,
        {
          x: margem,
          y,
          size: 12,
          font: bold,
          color:
            rgb(
              0.06,
              0.09,
              0.16,
            ),
        },
      );
    }

    function card(
      pagina: ReturnType<
        typeof pdf.addPage
      >,
      x: number,
      y: number,
      w: number,
      titulo: string,
      valor: string | number,
    ) {
      pagina.drawRectangle({
        x,
        y,
        width: w,
        height: 54,
        color: cinzaClaro,
        borderColor: borda,
        borderWidth: 0.8,
      });

      pagina.drawText(
        cortarTexto(
          titulo,
          bold,
          7.5,
          w - 20,
        ),
        {
          x: x + 10,
          y: y + 35,
          size: 7.5,
          font: bold,
          color: cinza,
        },
      );

      pagina.drawText(
        limparEspacosPdf(
          String(valor),
        ),
        {
          x: x + 10,
          y: y + 14,
          size: 15,
          font: bold,
          color:
            rgb(
              0.02,
              0.05,
              0.12,
            ),
        },
      );
    }

    const moeda =
      new Intl.NumberFormat(
        locale,
        {
          style:
            "currency",
          currency:
            "BRL",
        },
      );

    const pagina1 =
      pdf.addPage([
        largura,
        altura,
      ]);

    desenharCabecalho(
      pagina1,
    );

    const larguraCard =
      (
        largura -
        margem * 2 -
        36
      ) /
      4;

    let y =
      altura -
      125;

    tituloSecao(
      pagina1,
      r.circulacao,
      y,
    );

    y -= 68;

    [
      [
        r.emprestimos,
        dados.circulacao.emprestimos,
      ],
      [
        r.devolucoes,
        dados.circulacao.devolucoes,
      ],
      [
        r.renovacoes,
        dados.renovacoes.total,
      ],
      [
        r.reservas,
        dados.reservas.total,
      ],
    ].forEach(
      (
        item,
        indice,
      ) =>
        card(
          pagina1,
          margem +
            indice *
              (
                larguraCard +
                12
              ),
          y,
          larguraCard,
          String(
            item[0],
          ),
          item[1],
        ),
    );

    y -= 88;

    tituloSecao(
      pagina1,
      r.multas,
      y,
    );

    y -= 68;

    [
      [
        r.multasGeradas,
        dados.multas.quantidade,
      ],
      [
        r.valorGerado,
        moeda.format(
          dados.multas.valorGerado,
        ),
      ],
      [
        r.valorPago,
        moeda.format(
          dados.multas.valorPago,
        ),
      ],
      [
        r.valorAberto,
        moeda.format(
          dados.multas.valorEmAberto,
        ),
      ],
    ].forEach(
      (
        item,
        indice,
      ) =>
        card(
          pagina1,
          margem +
            indice *
              (
                larguraCard +
                12
              ),
          y,
          larguraCard,
          String(
            item[0],
          ),
          item[1],
        ),
    );

    y -= 88;

    tituloSecao(
      pagina1,
      r.acervo,
      y,
    );

    y -= 68;

    const disponiveis =
      dados.acervo.porStatus
        .DISPONIVEL ||
      0;

    const indisponiveis =
      Math.max(
        0,
        dados.acervo.exemplares -
          disponiveis,
      );

    [
      [
        r.titulos,
        dados.acervo.titulos,
      ],
      [
        r.exemplares,
        dados.acervo.exemplares,
      ],
      [
        r.disponiveis,
        disponiveis,
      ],
      [
        r.indisponiveis,
        indisponiveis,
      ],
    ].forEach(
      (
        item,
        indice,
      ) =>
        card(
          pagina1,
          margem +
            indice *
              (
                larguraCard +
                12
              ),
          y,
          larguraCard,
          String(
            item[0],
          ),
          item[1],
        ),
    );

    y -= 88;

    tituloSecao(
      pagina1,
      r.digital,
      y,
    );

    y -= 68;

    [
      [
        r.acessos,
        dados.digital.acessos,
      ],
      [
        r.usuariosUnicos,
        dados.digital.usuariosUnicos,
      ],
      [
        r.visualizacoes,
        dados.digital.visualizacoes,
      ],
      [
        r.leiturasConcluidas,
        dados.digital.leiturasConcluidas,
      ],
    ].forEach(
      (
        item,
        indice,
      ) =>
        card(
          pagina1,
          margem +
            indice *
              (
                larguraCard +
                12
              ),
          y,
          larguraCard,
          String(
            item[0],
          ),
          item[1],
        ),
    );

    const pagina2 =
      pdf.addPage([
        largura,
        altura,
      ]);

    desenharCabecalho(
      pagina2,
    );

    const metade =
      (
        largura -
        margem * 2 -
        24
      ) /
      2;

    function ranking(
      x: number,
      titulo: string,
      itens: Array<{
        principal: string;
        secundario: string;
        quantidade: number;
      }>,
    ) {
      let ry =
        altura -
        130;

      pagina2.drawText(
        titulo,
        {
          x,
          y: ry,
          size: 13,
          font: bold,
          color:
            rgb(
              0.06,
              0.09,
              0.16,
            ),
        },
      );

      ry -= 22;

      if (
        itens.length === 0
      ) {
        pagina2.drawText(
          r.semDados,
          {
            x,
            y: ry,
            size: 9,
            font: normal,
            color: cinza,
          },
        );

        return;
      }

      itens
        .slice(
          0,
          10,
        )
        .forEach(
          (
            item,
            indice,
          ) => {
            pagina2.drawRectangle({
              x,
              y:
                ry -
                42,
              width:
                metade,
              height: 48,
              color:
                indice %
                  2 ===
                0
                  ? azulClaro
                  : cinzaClaro,
              borderColor:
                borda,
              borderWidth:
                0.5,
            });

            pagina2.drawText(
              `${indice + 1}.`,
              {
                x:
                  x +
                  10,
                y:
                  ry -
                  11,
                size: 10,
                font: bold,
                color: azul,
              },
            );

            pagina2.drawText(
              cortarTexto(
                item.principal,
                bold,
                9,
                metade -
                  95,
              ),
              {
                x:
                  x +
                  34,
                y:
                  ry -
                  10,
                size: 9,
                font: bold,
                color:
                  rgb(
                    0.05,
                    0.08,
                    0.14,
                  ),
              },
            );

            if (
              item.secundario
            ) {
              pagina2.drawText(
                cortarTexto(
                  item.secundario,
                  normal,
                  7.5,
                  metade -
                    95,
                ),
                {
                  x:
                    x +
                    34,
                  y:
                    ry -
                    27,
                  size: 7.5,
                  font: normal,
                  color: cinza,
                },
              );
            }

            const qtd =
              `${item.quantidade} ${
                item.quantidade === 1
                  ? r.emprestimoQtd
                  : r.emprestimosQtd
              }`;

            pagina2.drawText(
              qtd,
              {
                x:
                  x +
                  metade -
                  78,
                y:
                  ry -
                  11,
                size: 8,
                font: bold,
                color: azul,
              },
            );

            ry -= 56;
          },
        );
    }

    ranking(
      margem,
      r.maisEmprestados,
      dados.rankings.itensMaisEmprestados.map(
        (
          item,
        ) => ({
          principal:
            item.titulo,
          secundario:
            item.subtitulo ||
            "",
          quantidade:
            item.quantidade,
        }),
      ),
    );

    ranking(
      margem +
        metade +
        24,
      r.usuariosAtivos,
      dados.rankings.usuariosMaisAtivos.map(
        (
          item,
        ) => ({
          principal:
            item.nome,
          secundario:
            item.email ||
            "",
          quantidade:
            item.quantidade,
        }),
      ),
    );

    const paginas =
      pdf.getPages();

    paginas.forEach(
      (
        pagina,
        indice,
      ) => {
        pagina.drawLine({
          start: {
            x: margem,
            y: 27,
          },
          end: {
            x:
              largura -
              margem,
            y: 27,
          },
          thickness:
            0.5,
          color: borda,
        });

        pagina.drawText(
          r.gerado,
          {
            x: margem,
            y: 14,
            size: 7.5,
            font: normal,
            color: cinza,
          },
        );

        const numero =
          `${r.pagina} ${indice + 1} ${r.de} ${paginas.length}`;

        pagina.drawText(
          numero,
          {
            x:
              largura -
              margem -
              normal.widthOfTextAtSize(
                numero,
                7.5,
              ),
            y: 14,
            size: 7.5,
            font: normal,
            color: cinza,
          },
        );
      },
    );

    const bytes =
      await pdf.save();

    const nomeArquivo =
      `biblioteca-relatorio-${dados.periodo.inicio}-${dados.periodo.fim}.pdf`;

    return new NextResponse(
      Buffer.from(
        bytes,
      ),
      {
        status: 200,

        headers: {
          "Content-Type":
            "application/pdf",

          "Content-Disposition":
            `attachment; filename="${nomeArquivo}"`,

          "Cache-Control":
            "no-store",
        },
      },
    );
  } catch (erro) {
    const resposta =
      respostaErroBiblioteca(
        erro,
      );

    return NextResponse.json(
      resposta.corpo,
      {
        status:
          resposta.status,
      },
    );
  }
}
