import type { LocalePhanyx } from "@/i18n/config";

export type ForeignLocale = Exclude<LocalePhanyx, "pt-BR">;

type Plan = { subtitle: string; description: string; period: string; units: string; ideal: string; features: string[] };
type Copy = {
  badge: string; headline: string; accent: string; intro: string; start: string; specialist: string;
  indicators: { title: string; description: string }[]; trust: string[];
  why: string; whyTitle: string; whyDescription: string;
  simulatorTitle: string; simulatorDescription: string; students: string; unitsLabel: string; unitHint: string;
  total: string; included: string; enterpriseUnits: string; perStudent: string;
  plans: [Plan, Plan, Plan]; recommended: string; advanced: string; includes: string; idealLabel: string;
  trialNote: string; compareLabel: string; compareTitle: string; compareDescription: string;
  comparison: { label: string; values: [string, string, string] }[];
  featureAvailability: string; finalTitle: string; finalDescription: string;
  freeTrial: string; proposal: string;
};

const yesNo = {
  "en-US": ["Yes", "No", "Basic", "Complete", "Advanced"],
  "es-ES": ["Sí", "No", "Básico", "Completo", "Avanzado"],
  "fr-FR": ["Oui", "Non", "Base", "Complet", "Avancé"],
  "pt-PT": ["Sim", "Não", "Base", "Completo", "Avançado"],
} as const;

const comparisonLabels: Record<ForeignLocale, string[]> = {
  "en-US": ["Academic management", "Student, teacher and admin portals", "LMS with lessons and materials", "Online exams", "Institutional finance", "Documents with QR codes", "Visual certificate editor", "Active certificate templates", "Certificates by program and course", "Certificates issued to students", "ID badge editor", "Batch badge issuance", "HR management", "PHANYX HR mobile time clock", "Institution mobile web app", "Photos, location and approved sites", "Time records and corrections", "Support priority", "Extended customization"],
  "es-ES": ["Gestión académica", "Áreas de estudiantes, docentes y administración", "LMS con clases y materiales", "Exámenes en línea", "Finanzas institucionales", "Documentos con código QR", "Editor visual de certificados", "Modelos de certificado activos", "Certificados por modalidad y curso", "Emisión de certificados", "Editor de acreditaciones", "Emisión de acreditaciones en lote", "Gestión de RR. HH.", "Control horario móvil PHANYX RH", "Aplicación web móvil institucional", "Fotos, ubicación y lugares autorizados", "Historial y correcciones de fichajes", "Prioridad de soporte", "Personalización ampliada"],
  "fr-FR": ["Gestion académique", "Espaces étudiants, enseignants et administration", "LMS avec cours et ressources", "Examens en ligne", "Finances de l'établissement", "Documents avec QR code", "Éditeur visuel de certificats", "Modèles de certificat actifs", "Certificats par parcours et cours", "Émission des certificats", "Éditeur de badges", "Émission de badges par lots", "Gestion RH", "Pointage mobile PHANYX RH", "Application web mobile de l'établissement", "Photos, localisation et lieux autorisés", "Historique et corrections de pointage", "Priorité du support", "Personnalisation étendue"],
  "pt-PT": ["Gestão académica", "Áreas de estudantes, docentes e administração", "LMS com aulas e materiais", "Provas online", "Finanças institucionais", "Documentos com QR Code", "Editor visual de certificados", "Modelos de certificado ativos", "Certificados por modalidade e curso", "Emissão de certificados", "Editor de cartões de identificação", "Emissão de cartões em lote", "Gestão de recursos humanos", "PHANYX RH Ponto Mobile", "Aplicação web móvel institucional", "Foto, localização e locais autorizados", "Histórico e correções de ponto", "Prioridade de apoio", "Personalização ampliada"],
};

function comparison(locale: ForeignLocale) {
  const [yes, no, basic, complete, advanced] = yesNo[locale];
  const rows: [string, string, string][] = [
    [yes, yes, yes], [yes, yes, yes], [basic, complete, complete], [no, yes, yes],
    [basic, yes, advanced], [no, yes, yes], [basic + " — 1", complete + " — 20", complete + " — ∞"],
    ["1", "20", "∞"], [no, yes, yes], [basic, "∞", "∞"],
    [no, complete, advanced], [no, yes, advanced], [basic, complete, advanced],
    [no, yes, advanced], [no, yes, advanced], [no, yes, advanced],
    [no, yes, advanced], [no, basic, advanced], [no, basic, yes],
  ];
  return comparisonLabels[locale].map((label, i) => ({ label, values: rows[i] }));
}

export const localizedPlans: Record<ForeignLocale, Copy> = {
  "en-US": {
    badge: "60 days free • Academic SaaS platform for real institutions", headline: "Try PHANYX free for 60 days", accent: "and bring modern management to your institution",
    intro: "Real institutions can start with 60 days of free use. Your team can test academic management, LMS, finance, documents, certificates, and student and teacher portals. After the trial, monthly billing follows the selected plan, active students and active units.",
    start: "Start 60-day free trial", specialist: "Talk to an expert",
    indicators: [
      { title: "Multiple institutions", description: "A SaaS architecture designed to keep institutional data separate." },
      { title: "Academics + LMS + finance", description: "One platform to reduce manual work and improve control." },
      { title: "Security and verification", description: "Roles, QR-coded documents and audit trails." },
      { title: "Scales with active students", description: "Pricing that follows the size of your operation." },
    ],
    trust: ["Built for real academic operations", "Separate admin, teacher and student roles", "Multi-institution SaaS architecture", "QR code document verification"],
    why: "WHY PHANYX", whyTitle: "Technology for institutions seeking growth and efficiency", whyDescription: "PHANYX brings academic management, LMS, finance and documents into one platform to reduce repeated work.",
    simulatorTitle: "Estimate the price after the 60-day trial", simulatorDescription: "Enter active students and units to see the estimated monthly amount in your local currency.",
    students: "Active students", unitsLabel: "Total active units", unitHint: "Include the contracting institution. Only active units with institutional access count.",
    total: "Estimated monthly total", included: "The units entered are included in this plan.", enterpriseUnits: "Units included and extra unit fees are specified in the contract.", perStudent: "per active student",
    plans: [
      { subtitle: "For institutions starting their digital organization", description: "An affordable, professional academic foundation that scales with active students.", period: "/month + USD 1 per active student + 1 active unit included", units: "The contracting institution is the first included unit. Each additional active unit costs USD 19 per month.", ideal: "Technical schools, independent courses and smaller institutions", features: ["Student, teacher, staff and course records", "Subjects, terms and classes", "Student enrollment", "Institutional departments", "Admin, teacher and student portals", "Secure role-based login", "Institutional finance", "Notices and holidays", "Basic institutional documents", "Basic certificate editor with 1 active template", "1 active unit included"] },
      { subtitle: "For institutions seeking stronger operations", description: "Broader academic operations with LMS, finance, verified documents and certificates.", period: "/month + USD 1.50 per active student + up to 3 active units included", units: "The contracting institution counts toward the 3 units. Each additional active unit costs USD 29 per month.", ideal: "Colleges, online programs and growing institutions", features: ["Everything in Essential", "Complete LMS with lessons, materials and progress", "Automatically graded online exams", "Certificate editor with up to 20 active templates", "Automatic certificates by program and course, with QR code", "Unlimited issuance and student portal access", "PHANYX ID badge editor", "Individual and batch badges with QR codes", "Complete HR: time, payroll, benefits, leave and termination", "Mobile time clock with photo, location and optional face recognition", "Authorized time record corrections and audit trail", "Contracts and documents with automatic fields", "Academic transcripts in PDF and the student portal", "Internal chat, ombudsman and PHANYX reputation", "Basic Google integrations", "Up to 3 active units included"] },
      { subtitle: "For institutions needing more scale and priority", description: "More institutional capacity, priority support, customization and advanced operations.", period: "/month + USD 2 per active student + units defined by contract", units: "Included units and extra unit fees are set in the commercial proposal.", ideal: "Universities, education groups and larger institutions", features: ["Everything in Professional", "Unlimited active certificate templates, including more than 20 at once", "Advanced certificates and badges across campuses", "Expanded institutional template customization", "Advanced HR and mobile time clock across campuses", "Expanded location, auditing and face recognition rules", "Advanced PHANYX Growth", "Institutional reputation dashboard and multiple channels", "Advanced Google and Meta integrations", "Google Business", "Institutional marketing and analytics", "Advanced campus management", "Exclusive customization and automation", "Advanced transcripts and audited documents", "Priority support and tailored commercial terms"] },
    ],
    recommended: "MOST POPULAR", advanced: "ADVANCED SCALE", includes: "Includes", idealLabel: "Ideal for", trialNote: "60-day free trial available after a proposal. Local currency terms are agreed before billing.",
    compareLabel: "COMPARISON", compareTitle: "Compare plans at a glance", compareDescription: "Choose a foundation and expand as your academic operation grows.", comparison: comparison("en-US"),
    featureAvailability: "Availability and pricing of new modules are confirmed in the commercial proposal.", finalTitle: "Ready to grow with PHANYX?", finalDescription: "Bring academic, commercial and administrative work together in one platform.", freeTrial: "Start a free trial", proposal: "Request a proposal",
  },
  "es-ES": {
    badge: "60 días gratis • Plataforma académica SaaS", headline: "Prueba PHANYX gratis durante 60 días", accent: "y moderniza la gestión de tu institución",
    intro: "Las instituciones pueden probar gestión académica, LMS, finanzas, documentos, certificados y portales de estudiantes y docentes durante 60 días. Después, la cuota mensual depende del plan, los estudiantes activos y las unidades.",
    start: "Iniciar prueba de 60 días", specialist: "Hablar con un especialista",
    indicators: [{ title: "Varias instituciones", description: "Datos separados para cada institución." }, { title: "Académico + LMS + finanzas", description: "Una plataforma para reducir el trabajo manual." }, { title: "Seguridad y validación", description: "Perfiles, documentos QR y auditoría." }, { title: "Escalable por estudiante", description: "El precio sigue el tamaño de la operación." }],
    trust: ["Preparado para operaciones académicas", "Áreas independientes por perfil", "SaaS para varias instituciones", "Documentos con QR"],
    why: "POR QUÉ PHANYX", whyTitle: "Tecnología para instituciones que buscan crecer", whyDescription: "PHANYX reúne gestión académica, LMS, finanzas y documentos para reducir tareas repetitivas.",
    simulatorTitle: "Calcula el importe tras los 60 días", simulatorDescription: "Introduce estudiantes y unidades activos para estimar el importe mensual en euros.", students: "Estudiantes activos", unitsLabel: "Total de unidades activas", unitHint: "Incluye la institución contratante. Solo cuentan las unidades activas con acceso.", total: "Total mensual estimado", included: "Las unidades indicadas están incluidas.", enterpriseUnits: "Las unidades y sus costes adicionales se fijan por contrato.", perStudent: "por estudiante activo",
    plans: [
      { subtitle: "Para instituciones que inician su organización digital", description: "Una base académica profesional y accesible que crece con los estudiantes activos.", period: "/mes + 0,75 € por estudiante activo + 1 unidad incluida", units: "La institución contratante es la primera unidad. Cada unidad adicional cuesta 15 € al mes.", ideal: "Escuelas técnicas, cursos e instituciones pequeñas", features: ["Registro de estudiantes, docentes, personal y cursos", "Asignaturas, periodos y grupos", "Matrículas", "Departamentos institucionales", "Portales de administración, docentes y estudiantes", "Acceso seguro por perfil", "Finanzas institucionales", "Avisos y festivos", "Documentos básicos", "Editor de certificados con 1 modelo activo", "1 unidad activa incluida"] },
      { subtitle: "Para instituciones que buscan una operación completa", description: "Gestión ampliada con LMS, finanzas, documentos validados y certificados.", period: "/mes + 1,25 € por estudiante activo + hasta 3 unidades incluidas", units: "La institución cuenta dentro de las 3 unidades. Cada unidad adicional cuesta 25 € al mes.", ideal: "Facultades, educación a distancia e instituciones en crecimiento", features: ["Todo lo incluido en Esencial", "LMS completo con clases, materiales y progreso", "Exámenes en línea con corrección automática", "Editor de certificados con hasta 20 modelos activos", "Certificados automáticos con código QR", "Emisiones ilimitadas y acceso en el portal", "Editor PHANYX de acreditaciones", "Emisión individual y en lotes", "RR. HH. con horario, nóminas, beneficios y vacaciones", "Control horario móvil con foto y ubicación", "Correcciones autorizadas y auditoría", "Contratos y documentos con campos automáticos", "Expediente académico en PDF y portal", "Chat, defensoría y reputación PHANYX", "Integraciones Google básicas", "Hasta 3 unidades activas incluidas"] },
      { subtitle: "Para instituciones con necesidades avanzadas", description: "Más capacidad, soporte prioritario y personalización.", period: "/mes + 1,75 € por estudiante activo + unidades según contrato", units: "Las unidades incluidas y adicionales se definen en la propuesta.", ideal: "Universidades, grupos educativos e instituciones grandes", features: ["Todo lo incluido en Profesional", "Modelos de certificado activos ilimitados: más de 20 a la vez", "Certificados y acreditaciones para varias sedes", "Modelos institucionales personalizables", "RR. HH. y control horario avanzados", "Reglas ampliadas de ubicación y auditoría", "PHANYX Growth avanzado", "Panel de reputación multicanal", "Integraciones Google y Meta avanzadas", "Google Business", "Marketing e indicadores", "Gestión avanzada de sedes", "Personalización y automatizaciones exclusivas", "Expedientes y documentos con auditoría", "Soporte prioritario y condiciones personalizadas"] },
    ],
    recommended: "MÁS RECOMENDADO", advanced: "ESCALA AVANZADA", includes: "Incluye", idealLabel: "Ideal para", trialNote: "Prueba de 60 días disponible tras una propuesta. Las condiciones en euros se acuerdan antes de facturar.",
    compareLabel: "COMPARATIVA", compareTitle: "Compara los planes", compareDescription: "Elige una base y amplíala a medida que crece tu institución.", comparison: comparison("es-ES"),
    featureAvailability: "La disponibilidad y los precios de los nuevos módulos se confirman en la propuesta comercial.", finalTitle: "¿Listo para crecer con PHANYX?", finalDescription: "Unifica tus operaciones académicas, comerciales y administrativas.", freeTrial: "Iniciar prueba gratuita", proposal: "Solicitar propuesta",
  },
  "fr-FR": {
    badge: "60 jours gratuits • Plateforme académique SaaS", headline: "Essayez PHANYX pendant 60 jours gratuits", accent: "et modernisez la gestion de votre établissement",
    intro: "Votre équipe peut essayer la gestion académique, le LMS, les finances, les documents, les certificats et les espaces étudiants et enseignants. Ensuite, la facturation dépend de l'offre, des étudiants actifs et des unités.",
    start: "Commencer l'essai de 60 jours", specialist: "Parler à un spécialiste",
    indicators: [{ title: "Plusieurs établissements", description: "Séparation des données par établissement." }, { title: "Académique + LMS + finances", description: "Une plateforme pour réduire les tâches manuelles." }, { title: "Sécurité et validation", description: "Rôles, documents QR et audit." }, { title: "Évolutif par étudiant", description: "Une tarification adaptée à l'activité." }],
    trust: ["Conçu pour la gestion académique", "Espaces séparés par profil", "Architecture SaaS multi-établissements", "Validation des documents par QR"],
    why: "POURQUOI PHANYX", whyTitle: "Une technologie pour accompagner la croissance", whyDescription: "PHANYX réunit gestion académique, LMS, finances et documents pour réduire les tâches répétitives.",
    simulatorTitle: "Estimez le prix après 60 jours", simulatorDescription: "Indiquez les étudiants et unités actifs pour voir une estimation en euros.", students: "Étudiants actifs", unitsLabel: "Total des unités actives", unitHint: "Incluez l'établissement contractant. Seules les unités actives sont comptées.", total: "Total mensuel estimé", included: "Les unités indiquées sont incluses.", enterpriseUnits: "Les unités et leurs frais supplémentaires sont définis par contrat.", perStudent: "par étudiant actif",
    plans: [
      { subtitle: "Pour démarrer la transition numérique", description: "Une base académique professionnelle et accessible qui évolue avec les étudiants actifs.", period: "/mois + 0,75 € par étudiant actif + 1 unité incluse", units: "L'établissement contractant est la première unité. Chaque unité supplémentaire coûte 15 € par mois.", ideal: "Écoles techniques, cours et petits établissements", features: ["Dossiers des étudiants, enseignants, employés et cours", "Matières, périodes et classes", "Inscriptions", "Services de l'établissement", "Espaces admin, enseignants et étudiants", "Connexion sécurisée par rôle", "Finances de l'établissement", "Annonces et jours fériés", "Documents institutionnels de base", "Éditeur de certificats avec 1 modèle actif", "1 unité active incluse"] },
      { subtitle: "Pour des opérations plus complètes", description: "Gestion élargie avec LMS, finances, documents validés et certificats.", period: "/mois + 1,25 € par étudiant actif + jusqu'à 3 unités incluses", units: "L'établissement compte parmi les 3 unités. Chaque unité supplémentaire coûte 25 € par mois.", ideal: "Universités, enseignement en ligne et établissements en croissance", features: ["Tout Essentiel", "LMS complet avec cours, ressources et progression", "Examens en ligne corrigés automatiquement", "Éditeur de certificats avec 20 modèles actifs au maximum", "Certificats automatiques avec QR code", "Émission illimitée et accès étudiant", "Éditeur de badges PHANYX", "Émission individuelle et par lots", "RH : pointage, paie, avantages et congés", "Pointage mobile avec photo et localisation", "Corrections autorisées et audit", "Contrats et documents à champs automatiques", "Relevés académiques en PDF et dans l'espace étudiant", "Chat, médiation et réputation PHANYX", "Intégrations Google de base", "Jusqu'à 3 unités actives incluses"] },
      { subtitle: "Pour les établissements à grande échelle", description: "Plus de capacité, de personnalisation et un support prioritaire.", period: "/mois + 1,75 € par étudiant actif + unités définies par contrat", units: "Les unités incluses et supplémentaires sont précisées dans la proposition.", ideal: "Universités, groupes et grands établissements", features: ["Tout Professionnel", "Modèles de certificat actifs illimités, plus de 20 simultanément", "Certificats et badges multi-campus", "Modèles institutionnels personnalisables", "RH et pointage mobile avancés", "Règles étendues de localisation et d'audit", "PHANYX Growth avancé", "Tableau de réputation multicanal", "Intégrations Google et Meta avancées", "Google Business", "Marketing et indicateurs", "Gestion multi-campus", "Personnalisation et automatisations exclusives", "Relevés et documents avec audit", "Support prioritaire et conditions adaptées"] },
    ],
    recommended: "LE PLUS RECOMMANDÉ", advanced: "ÉCHELLE AVANCÉE", includes: "Inclus", idealLabel: "Idéal pour", trialNote: "Essai gratuit de 60 jours après accord sur la proposition. La facturation en euros est confirmée avant activation.",
    compareLabel: "COMPARATIF", compareTitle: "Comparez les offres", compareDescription: "Commencez avec une base solide et évoluez avec votre établissement.", comparison: comparison("fr-FR"),
    featureAvailability: "La disponibilité et le prix des nouveaux modules sont précisés dans la proposition commerciale.", finalTitle: "Prêt à évoluer avec PHANYX ?", finalDescription: "Réunissez les opérations académiques, commerciales et administratives.", freeTrial: "Commencer l'essai gratuit", proposal: "Demander un devis",
  },
  "pt-PT": {
    badge: "60 dias grátis • Plataforma académica SaaS", headline: "Experimente o PHANYX por 60 dias grátis", accent: "e modernize a gestão da sua instituição",
    intro: "As instituições podem experimentar gestão académica, LMS, finanças, documentos, certificados e áreas de estudantes e docentes. Depois, a mensalidade depende do plano, estudantes ativos e unidades.",
    start: "Começar 60 dias grátis", specialist: "Falar com um especialista",
    indicators: [{ title: "Várias instituições", description: "Dados separados por instituição." }, { title: "Académico + LMS + finanças", description: "Uma plataforma que reduz trabalho repetido." }, { title: "Segurança e validação", description: "Perfis, documentos QR e auditoria." }, { title: "Escalável por estudante", description: "O preço acompanha a operação." }],
    trust: ["Preparado para operações académicas", "Áreas independentes por perfil", "SaaS multi-instituição", "Validação de documentos com QR Code"],
    why: "PORQUÊ PHANYX", whyTitle: "Tecnologia para instituições em crescimento", whyDescription: "O PHANYX reúne gestão académica, LMS, finanças e documentos para reduzir trabalho repetido.",
    simulatorTitle: "Simule o valor após os 60 dias", simulatorDescription: "Indique os estudantes e unidades ativas para ver o valor mensal estimado em euros.", students: "Estudantes ativos", unitsLabel: "Total de unidades ativas", unitHint: "Inclua a instituição contratante. Só contam as unidades ativas com acesso.", total: "Total mensal estimado", included: "As unidades indicadas estão incluídas.", enterpriseUnits: "As unidades e os custos adicionais são definidos no contrato.", perStudent: "por estudante ativo",
    plans: [
      { subtitle: "Para instituições que iniciam a organização digital", description: "Uma base académica profissional e acessível que cresce com os estudantes ativos.", period: "/mês + 0,75 € por estudante ativo + 1 unidade incluída", units: "A instituição contratante é a primeira unidade. Cada unidade adicional custa 15 € por mês.", ideal: "Escolas técnicas, cursos e instituições menores", features: ["Registo de estudantes, docentes, funcionários e cursos", "Disciplinas, períodos e turmas", "Matrículas", "Setores institucionais", "Áreas de administração, docentes e estudantes", "Acesso seguro por perfil", "Finanças institucionais", "Avisos e feriados", "Documentos básicos", "Editor de certificados com 1 modelo ativo", "1 unidade ativa incluída"] },
      { subtitle: "Para instituições que querem operações completas", description: "Gestão ampliada com LMS, finanças, documentos validados e certificados.", period: "/mês + 1,25 € por estudante ativo + até 3 unidades incluídas", units: "A instituição está incluída nas 3 unidades. Cada unidade adicional custa 25 € por mês.", ideal: "Faculdades, EAD e instituições em crescimento", features: ["Tudo do plano Essencial", "LMS completo com aulas, materiais e progresso", "Provas online com correção automática", "Editor de certificados com até 20 modelos ativos", "Certificados automáticos com QR Code", "Emissões ilimitadas e acesso do estudante", "Editor PHANYX de cartões de identificação", "Emissão individual ou em lote", "RH com ponto, salários, benefícios e férias", "Ponto Mobile com foto e localização", "Correções autorizadas e auditoria", "Contratos e documentos com campos automáticos", "Histórico académico em PDF e na área do estudante", "Chat, ouvidoria e reputação PHANYX", "Integrações Google básicas", "Até 3 unidades ativas incluídas"] },
      { subtitle: "Para instituições que precisam de maior escala", description: "Mais capacidade, personalização e apoio prioritário.", period: "/mês + 1,75 € por estudante ativo + unidades definidas em contrato", units: "As unidades incluídas e adicionais são definidas na proposta comercial.", ideal: "Universidades, grupos educacionais e grandes instituições", features: ["Tudo do plano Profissional", "Modelos ativos de certificado ilimitados, mais de 20 em simultâneo", "Certificados e cartões avançados para vários polos", "Modelos institucionais personalizados", "RH e Ponto Mobile avançados", "Regras ampliadas de localização e auditoria", "PHANYX Growth avançado", "Painel de reputação multicanal", "Integrações Google e Meta avançadas", "Google Business", "Marketing e indicadores", "Gestão avançada de polos", "Personalizações e automatizações exclusivas", "Histórico e documentos com auditoria", "Apoio prioritário e condições personalizadas"] },
    ],
    recommended: "MAIS RECOMENDADO", advanced: "ESCALA AVANÇADA", includes: "Inclui", idealLabel: "Ideal para", trialNote: "Teste gratuito de 60 dias após proposta. A faturação em euros é acordada antes da ativação.",
    compareLabel: "COMPARATIVO", compareTitle: "Compare os planos", compareDescription: "Comece com uma base sólida e evolua com a sua instituição.", comparison: comparison("pt-PT"),
    featureAvailability: "A disponibilidade e o preço dos novos módulos são confirmados na proposta comercial.", finalTitle: "Pronto para crescer com o PHANYX?", finalDescription: "Reúna as operações académicas, comerciais e administrativas.", freeTrial: "Começar teste gratuito", proposal: "Pedir proposta",
  },
};
