export function criarEventoAgenda({
  id,
  tipo,
  data,
  hora = "",
  curso = "",
  turma = "",
  disciplina = "",
  professor = "",
  funcionario = "",
  departamento = "",
  polo = "",
  titulo = "",
  evento = "",
  descricao = "",
  responsavel = "",
  local = "",
  observacoes = "",
  status = "",
}: any) {
  return {
    id,
    tipo,
    data,
    hora,
    curso,
    turma,
    disciplina,
    professor,
    funcionario,
    departamento,
    polo,
    titulo,
    evento: evento || titulo,
    descricao,
    responsavel,
    local,
    observacoes,
    status,
  };
}